version: "3"
services:
  #discovey-eureka-8761
  peer1:
    image: repo.orders.com:5000/orders/discovery:latest
    deploy: 
      replicas: 1
      resources:  
        limits: 
          cpus: "0.2"
          memory: 512M
      restart_policy:
        condition: on-failure
    ports:
      - "8761:8080"
    environment:
      EXT_JAVA_OPTS: "-Dspring.profiles.active=peer1"
  #discovey-eureka-8762
  peer2:
    image: repo.orders.com:5000/orders/discovery:latest
    deploy: 
      replicas: 1
      resources:  
        limits: 
          cpus: "0.2"
          memory: 512M
      restart_policy:
        condition: on-failure
    ports:
      - "8762:8080"
    environment:
      EXT_JAVA_OPTS: "-Dspring.profiles.active=peer2"
#networks: 
#  default:
#    external: true
      
         